export const phrases = [
    "welcome to hell",
    "welcome to paradise",
    "since '03",
    "recursing...",
    "works on my machine",
    "shipping it anyway",
    "you again",
    "99% done (forever)",
    "typo here",
    "it's not a bug",
    "everything is a draft",
    "please clap",
    "still cheaper than therapy",
    "rendered at 3am",
    "undefined is not a function",
    "have you tried turning it off",
    "lovingly(?) arranged",
    "now with 12 unread errors",
    "merge conflicts and chill",
    "where's the fucking coffee man!?",
    "deploying on a friday",
    "like a totally normal young man does...",
    ";)",
    "the whitespace is breathing",
    "accidentally became the regex",
    "the void returned my PR",
    "the cursor blinks on its own",
    "we live inside a try block",
    "the daemon told me to",
    "garbage collecting",
    "the build passed but at what cost",
];
